
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-5
pull_requests: [{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"MC-RecPut","number":74,"title":"made PUT and tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/74"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"MD-RecDel","number":73,"title":"Added del function and tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/73"},{"author":{"id":"U_kgDOBXm5-g","is_bot":false,"login":"walexgreen","name":"William Greenwald"},"headRefName":"William-HelpRequest-Delete","number":72,"title":"HelpRequest DELETE completed","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/72"}]
