
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-5
pull_requests: [{"author":{"id":"U_kgDOBdlAFQ","is_bot":false,"login":"maidang111","name":""},"headRefName":"MD-RecommendationRequestController","number":64,"title":"Added Get and Post Endpoints for RecommendationRequestController","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/64"},{"author":{"id":"U_kgDOBXm5-g","is_bot":false,"login":"walexgreen","name":"William Greenwald"},"headRefName":"William-HelpRequest","number":63,"title":"wg - created the items for issue#32, working on local host","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/63"},{"author":{"id":"U_kgDOBdlAFQ","is_bot":false,"login":"maidang111","name":""},"headRefName":"MD-RecommendationRequest-create-db","number":61,"title":"Created RecommendationRequest-DB","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/61"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-ArticlePut","number":48,"title":"Articles: PUT ","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/48"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-ArticleDel","number":47,"title":"Articles: Added delete","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/47"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-ArticlesGet","number":46,"title":"Articles: Add Get by Id ","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/46"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-ArticlesController","number":45,"title":"Articles Controller: Get All and Post","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/45"}]
