
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-5
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxMzYwOTU1","is_bot":false,"login":"rileychou","name":"Riley Chou"},"headRefName":"Riley-DiningCommonsMenuItemsTable","number":44,"title":"rc - Create database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/44"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-Articles-create-db","number":43,"title":"Create Articles database table","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-5/pull/43"}]
